// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIr6XJjyeoQ1ErpPZiqq1eEYEI0Cob6i0',
    appId: '1:722105896871:web:5672616f8bc8cefc3b7082',
    messagingSenderId: '722105896871',
    projectId: 'smart-travel-planner-ceacd',
    authDomain: 'smart-travel-planner-ceacd.firebaseapp.com',
    storageBucket: 'smart-travel-planner-ceacd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuTn4htd8TlgjvmRv8wxsuwnsCQrh-4Sk',
    appId: '1:722105896871:android:3c77050e04eb4fe63b7082',
    messagingSenderId: '722105896871',
    projectId: 'smart-travel-planner-ceacd',
    storageBucket: 'smart-travel-planner-ceacd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNcJMCOigMP0tTUc_8TOUyoWSRDfqgti0',
    appId: '1:722105896871:ios:9ee1aa40ad4056ee3b7082',
    messagingSenderId: '722105896871',
    projectId: 'smart-travel-planner-ceacd',
    storageBucket: 'smart-travel-planner-ceacd.firebasestorage.app',
    iosBundleId: 'com.example.smartTravelPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNcJMCOigMP0tTUc_8TOUyoWSRDfqgti0',
    appId: '1:722105896871:ios:9ee1aa40ad4056ee3b7082',
    messagingSenderId: '722105896871',
    projectId: 'smart-travel-planner-ceacd',
    storageBucket: 'smart-travel-planner-ceacd.firebasestorage.app',
    iosBundleId: 'com.example.smartTravelPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIr6XJjyeoQ1ErpPZiqq1eEYEI0Cob6i0',
    appId: '1:722105896871:web:c0817fdfdd22fb213b7082',
    messagingSenderId: '722105896871',
    projectId: 'smart-travel-planner-ceacd',
    authDomain: 'smart-travel-planner-ceacd.firebaseapp.com',
    storageBucket: 'smart-travel-planner-ceacd.firebasestorage.app',
  );
}
