// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUtI1l2k9grTpzR4QhPkZ4C5zEH2T6Hws',
    appId: '1:1030876459850:web:41d7a4ed715fe6f91ec7b3',
    messagingSenderId: '1030876459850',
    projectId: 'smart-travel-planner-bq',
    authDomain: 'smart-travel-planner-bq.firebaseapp.com',
    storageBucket: 'smart-travel-planner-bq.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJy3yWS2Eu8kE8nehL-eHO9EYh4yFnVAY',
    appId: '1:1030876459850:android:d53806fc47a73d3e1ec7b3',
    messagingSenderId: '1030876459850',
    projectId: 'smart-travel-planner-bq',
    storageBucket: 'smart-travel-planner-bq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7k1-sgBac2D9aQmUMn5IX4OFdfHTQtzo',
    appId: '1:1030876459850:ios:bdf64669bba505771ec7b3',
    messagingSenderId: '1030876459850',
    projectId: 'smart-travel-planner-bq',
    storageBucket: 'smart-travel-planner-bq.firebasestorage.app',
    iosBundleId: 'com.example.smartTravelPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7k1-sgBac2D9aQmUMn5IX4OFdfHTQtzo',
    appId: '1:1030876459850:ios:bdf64669bba505771ec7b3',
    messagingSenderId: '1030876459850',
    projectId: 'smart-travel-planner-bq',
    storageBucket: 'smart-travel-planner-bq.firebasestorage.app',
    iosBundleId: 'com.example.smartTravelPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUtI1l2k9grTpzR4QhPkZ4C5zEH2T6Hws',
    appId: '1:1030876459850:web:ed92b9f966df429e1ec7b3',
    messagingSenderId: '1030876459850',
    projectId: 'smart-travel-planner-bq',
    authDomain: 'smart-travel-planner-bq.firebaseapp.com',
    storageBucket: 'smart-travel-planner-bq.firebasestorage.app',
  );

}